import './globals.css'
import { Flowbite, ThemeModeScript } from "flowbite-react";
import { Inter } from "next/font/google";
import { type FC, type PropsWithChildren } from "react";
import { twMerge } from "tailwind-merge";

export const metadata = {
    title: 'Admin dashboard',
    description: 'Generated by Next.js',
}

const inter = Inter({ subsets: ["latin"] });

const RootLayout: FC<PropsWithChildren> = function ({ children }) {
    return (
        <html lang="en">
            <head>
                <ThemeModeScript />
            </head>
            <body className={twMerge("bg-gray-50 dark:bg-gray-900", inter.className)}>
                {children}
            </body>
        </html>
    );
};

export default RootLayout;